// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwjCKZFw5Dg3MWd6fTBNsefcHIP979lhA',
    appId: '1:243973317631:web:5cfc645f2ed437e9783dca',
    messagingSenderId: '243973317631',
    projectId: 'cursapp-7567a',
    authDomain: 'cursapp-7567a.firebaseapp.com',
    storageBucket: 'cursapp-7567a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaai4BgdGS7MjZVZw_DgCobfNKvWnUwJ8',
    appId: '1:243973317631:android:f740f0ba9c47a05d783dca',
    messagingSenderId: '243973317631',
    projectId: 'cursapp-7567a',
    storageBucket: 'cursapp-7567a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADIsnw-8XN4eUQNsaU2BLFUlB4CtNbaXA',
    appId: '1:243973317631:ios:daedff121a04d913783dca',
    messagingSenderId: '243973317631',
    projectId: 'cursapp-7567a',
    storageBucket: 'cursapp-7567a.firebasestorage.app',
    iosBundleId: 'com.example.cursapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADIsnw-8XN4eUQNsaU2BLFUlB4CtNbaXA',
    appId: '1:243973317631:ios:daedff121a04d913783dca',
    messagingSenderId: '243973317631',
    projectId: 'cursapp-7567a',
    storageBucket: 'cursapp-7567a.firebasestorage.app',
    iosBundleId: 'com.example.cursapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwjCKZFw5Dg3MWd6fTBNsefcHIP979lhA',
    appId: '1:243973317631:web:d53340060f070a50783dca',
    messagingSenderId: '243973317631',
    projectId: 'cursapp-7567a',
    authDomain: 'cursapp-7567a.firebaseapp.com',
    storageBucket: 'cursapp-7567a.firebasestorage.app',
  );
}
